package com.example.computerz.myapplication;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Rect;
import android.util.AttributeSet;
import android.view.SurfaceView;

import java.util.*;

/**
 * Created by Nathan Tibbetts on 3/28/2017
 * this creates every single pixel in the drawing
 * each pixel is just a Custom Rectangle the I named either outline, right eye, left eye, right cheek, left cheek, or mouth
 * the methods are careful to group the pixels together that belong
 */

public class ColorsCaboom extends SurfaceView {

    //for some unknown reason, I'm not allowed to make an array, I will carry on and draw this whole thing without one!
    //an array would have been extremely useful when making this, I'll have to find out later why it wasn't allowed
    //here are all the pixels that make up the drawing, each labeled accordingly
    int x = 25;


    private CustomRect outline0 = new CustomRect("Outline", Color.BLACK, 0 * x, 0 * x, 1 * x, 1 * x);
    private CustomRect outline1 = new CustomRect("Outline", Color.BLACK, 0 * x, 1 * x, 1 * x, 2 * x);
    private CustomRect outline2 = new CustomRect("Outline", Color.BLACK, 0 * x, 2 * x, 1 * x, 3 * x);
    private CustomRect outline3 = new CustomRect("Outline", Color.BLACK, 0 * x, 3 * x, 1 * x, 4 * x);
    private CustomRect outline4 = new CustomRect("Outline", Color.BLACK, 0 * x, 4 * x, 1 * x, 5 * x);
    private CustomRect outline5 = new CustomRect("Outline", Color.BLACK, 0 * x, 5 * x, 1 * x, 6 * x);
    private CustomRect outline6 = new CustomRect("Outline", Color.BLACK, 1 * x, 0 * x, 2 * x, 1 * x);
    private CustomRect outline7 = new CustomRect("Outline", Color.BLACK, 1 * x, 1 * x, 2 * x, 2 * x);
    private CustomRect outline8 = new CustomRect("Outline", Color.BLACK, 1 * x, 2 * x, 2 * x, 3 * x);
    private CustomRect outline9 = new CustomRect("Outline", Color.BLACK, 1 * x, 3 * x, 2 * x, 4 * x);
    private CustomRect outline10 = new CustomRect("Outline", Color.BLACK, 1 * x, 4 * x, 2 * x, 5 * x);
    private CustomRect outline11 = new CustomRect("Outline", Color.BLACK, 1 * x, 5 * x, 2 * x, 6 * x);
    private CustomRect outline12 = new CustomRect("Outline", Color.BLACK, 1 * x, 6 * x, 2 * x, 7 * x);
    private CustomRect outline13 = new CustomRect("Outline", Color.BLACK, 1 * x, 7 * x, 2 * x, 8 * x);
    private CustomRect outline14 = new CustomRect("Outline", Color.BLACK, 2 * x, 0 * x, 3 * x, 1 * x);
    private CustomRect outline15 = new CustomRect("Outline", Color.BLACK, 2 * x, 1 * x, 3 * x, 2 * x);
    private CustomRect outline16 = new CustomRect("Outline", Color.BLACK, 2 * x, 2 * x, 3 * x, 3 * x);
    private CustomRect outline17 = new CustomRect("Outline", Color.BLACK, 2 * x, 3 * x, 3 * x, 4 * x);
    private CustomRect outline18 = new CustomRect("Outline", Color.BLACK, 2 * x, 4 * x, 3 * x, 5 * x);
    private CustomRect outline19 = new CustomRect("Outline", Color.BLACK, 2 * x, 5 * x, 3 * x, 6 * x);
    private CustomRect outline20 = new CustomRect("Outline", Color.BLACK, 2 * x, 6 * x, 3 * x, 7 * x);
    private CustomRect outline21 = new CustomRect("Outline", Color.BLACK, 2 * x, 7 * x, 3 * x, 8 * x);
    private CustomRect outline22 = new CustomRect("Outline", Color.BLACK, 2 * x, 8 * x, 3 * x, 9 * x);
    private CustomRect outline23 = new CustomRect("Outline", Color.BLACK, 2 * x, 9 * x, 3 * x, 10 * x);
    private CustomRect outline24 = new CustomRect("Outline", Color.BLACK, 3 * x, 0 * x, 4 * x, 1 * x);
    private CustomRect outline25 = new CustomRect("Outline", Color.BLACK, 3 * x, 1 * x, 4 * x, 2 * x);
    private CustomRect outline26 = new CustomRect("Outline", Color.BLACK, 3 * x, 2 * x, 4 * x, 3 * x);
    private CustomRect outline27 = new CustomRect("Outline", Color.BLACK, 3 * x, 3 * x, 4 * x, 4 * x);
    private CustomRect outline28 = new CustomRect("Outline", Color.BLACK, 3 * x, 4 * x, 4 * x, 5 * x);
    private CustomRect outline29 = new CustomRect("Outline", Color.BLACK, 3 * x, 5 * x, 4 * x, 6 * x);
    private CustomRect outline30 = new CustomRect("Outline", Color.BLACK, 3 * x, 6 * x, 4 * x, 7 * x);
    private CustomRect outline31 = new CustomRect("Outline", Color.BLACK, 3 * x, 7 * x, 4 * x, 8 * x);
    private CustomRect outline32 = new CustomRect("Outline", Color.BLACK, 3 * x, 8 * x, 4 * x, 9 * x);
    private CustomRect outline33 = new CustomRect("Outline", Color.BLACK, 3 * x, 9 * x, 4 * x, 10 * x);
    private CustomRect outline34 = new CustomRect("Outline", Color.BLACK, 3 * x, 10 * x, 4 * x, 11 * x);
    private CustomRect outline35 = new CustomRect("Outline", Color.BLACK, 4 * x, 1 * x, 5 * x, 2 * x);
    private CustomRect outline36 = new CustomRect("Outline", Color.BLACK, 4 * x, 2 * x, 5 * x, 3 * x);
    private CustomRect outline37 = new CustomRect("Outline", Color.BLACK, 4 * x, 3 * x, 5 * x, 4 * x);
    private CustomRect outline38 = new CustomRect("Outline", Color.BLACK, 4 * x, 4 * x, 5 * x, 5 * x);
    private CustomRect outline39 = new CustomRect("Outline", Color.BLACK, 4 * x, 5 * x, 5 * x, 6 * x);
    private CustomRect outline40 = new CustomRect("Outline", Color.BLACK, 4 * x, 6 * x, 5 * x, 7 * x);
    private CustomRect outline41 = new CustomRect("Outline", Color.BLACK, 4 * x, 7 * x, 5 * x, 8 * x);
    private CustomRect outline42 = new CustomRect("Outline", Color.BLACK, 4 * x, 8 * x, 5 * x, 9 * x);
    private CustomRect outline43 = new CustomRect("Outline", Color.BLACK, 4 * x, 9 * x, 5 * x, 10 * x);
    private CustomRect outline44 = new CustomRect("Outline", Color.BLACK, 4 * x, 10 * x, 5 * x, 11 * x);
    private CustomRect outline45 = new CustomRect("Outline", Color.BLACK, 4 * x, 11 * x, 5 * x, 12 * x);
    private CustomRect outline46 = new CustomRect("Outline", Color.BLACK, 4 * x, 24 * x, 5 * x, 25 * x);
    private CustomRect outline47 = new CustomRect("Outline", Color.BLACK, 4 * x, 25 * x, 5 * x, 26 * x);
    private CustomRect outline48 = new CustomRect("Outline", Color.BLACK, 4 * x, 26 * x, 5 * x, 27 * x);
    private CustomRect outline49 = new CustomRect("Outline", Color.BLACK, 4 * x, 27 * x, 5 * x, 28 * x);
    private CustomRect outline50 = new CustomRect("Outline", Color.BLACK, 4 * x, 28 * x, 5 * x, 29 * x);
    private CustomRect outline51 = new CustomRect("Outline", Color.BLACK, 4 * x, 29 * x, 5 * x, 30 * x);
    private CustomRect outline52 = new CustomRect("Outline", Color.BLACK, 4 * x, 30 * x, 5 * x, 31 * x);
    private CustomRect outline53 = new CustomRect("Outline", Color.BLACK, 5 * x, 1 * x, 6 * x, 2 * x);
    private CustomRect outline54 = new CustomRect("Outline", Color.BLACK, 5 * x, 2 * x, 6 * x, 3 * x);
    private CustomRect outline55 = new CustomRect("Outline", Color.BLACK, 5 * x, 3 * x, 6 * x, 4 * x);
    private CustomRect outline56 = new CustomRect("Outline", Color.BLACK, 5 * x, 4 * x, 6 * x, 5 * x);
    private CustomRect outline57 = new CustomRect("Outline", Color.BLACK, 5 * x, 12 * x, 6 * x, 13 * x);
    private CustomRect outline58 = new CustomRect("Outline", Color.BLACK, 5 * x, 15 * x, 6 * x, 16 * x);
    private CustomRect outline59 = new CustomRect("Outline", Color.BLACK, 5 * x, 16 * x, 6 * x, 17 * x);
    private CustomRect outline60 = new CustomRect("Outline", Color.BLACK, 5 * x, 17 * x, 6 * x, 18 * x);
    private CustomRect outline61 = new CustomRect("Outline", Color.BLACK, 5 * x, 18 * x, 6 * x, 19 * x);
    private CustomRect outline62 = new CustomRect("Outline", Color.BLACK, 5 * x, 19 * x, 6 * x, 20 * x);
    private CustomRect outline63 = new CustomRect("Outline", Color.BLACK, 5 * x, 20 * x, 6 * x, 21 * x);
    private CustomRect outline64 = new CustomRect("Outline", Color.BLACK, 5 * x, 21 * x, 6 * x, 22 * x);
    private CustomRect outline65 = new CustomRect("Outline", Color.BLACK, 5 * x, 22 * x, 6 * x, 23 * x);
    private CustomRect outline66 = new CustomRect("Outline", Color.BLACK, 5 * x, 23 * x, 6 * x, 24 * x);
    private CustomRect outline67 = new CustomRect("Outline", Color.BLACK, 5 * x, 26 * x, 6 * x, 27 * x);
    private CustomRect outline68 = new CustomRect("Outline", Color.BLACK, 5 * x, 31 * x, 6 * x, 32 * x);
    private CustomRect outline69 = new CustomRect("Outline", Color.BLACK, 6 * x, 1 * x, 7 * x, 2 * x);
    private CustomRect outline70 = new CustomRect("Outline", Color.BLACK, 6 * x, 2 * x, 7 * x, 3 * x);
    private CustomRect outline71 = new CustomRect("Outline", Color.BLACK, 6 * x, 12 * x, 7 * x, 13 * x);
    private CustomRect outline72 = new CustomRect("Outline", Color.BLACK, 6 * x, 13 * x, 7 * x, 14 * x);
    private CustomRect outline73 = new CustomRect("Outline", Color.BLACK, 6 * x, 14 * x, 7 * x, 15 * x);
    private CustomRect outline74 = new CustomRect("Outline", Color.BLACK, 6 * x, 25 * x, 7 * x, 26 * x);
    private CustomRect outline75 = new CustomRect("Outline", Color.BLACK, 6 * x, 32 * x, 7 * x, 33 * x);
    private CustomRect outline76 = new CustomRect("Outline", Color.BLACK, 7 * x, 2 * x, 8 * x, 3 * x);
    private CustomRect outline77 = new CustomRect("Outline", Color.BLACK, 7 * x, 12 * x, 8 * x, 13 * x);
    private CustomRect outline78 = new CustomRect("Outline", Color.BLACK, 7 * x, 25 * x, 8 * x, 26 * x);
    private CustomRect outline79 = new CustomRect("Outline", Color.BLACK, 7 * x, 32 * x, 8 * x, 33 * x);
    private CustomRect outline80 = new CustomRect("Outline", Color.BLACK, 7 * x, 33 * x, 8 * x, 34 * x);
    private CustomRect outline81 = new CustomRect("Outline", Color.BLACK, 8 * x, 2 * x, 9 * x, 3 * x);
    private CustomRect outline82 = new CustomRect("Outline", Color.BLACK, 8 * x, 11 * x, 9 * x, 12 * x);
    private CustomRect outline83 = new CustomRect("Outline", Color.BLACK, 8 * x, 25 * x, 9 * x, 26 * x);
    private CustomRect outline84 = new CustomRect("Outline", Color.BLACK, 8 * x, 32 * x, 9 * x, 33 * x);
    private CustomRect outline85 = new CustomRect("Outline", Color.BLACK, 8 * x, 34 * x, 9 * x, 35 * x);
    private CustomRect outline86 = new CustomRect("Outline", Color.BLACK, 9 * x, 3 * x, 10 * x, 4 * x);
    private CustomRect outline87 = new CustomRect("Outline", Color.BLACK, 9 * x, 25 * x, 10 * x, 26 * x);
    private CustomRect outline88 = new CustomRect("Outline", Color.BLACK, 9 * x, 32 * x, 10 * x, 33 * x);
    private CustomRect outline89 = new CustomRect("Outline", Color.BLACK, 9 * x, 34 * x, 10 * x, 35 * x);
    private CustomRect outline90 = new CustomRect("Outline", Color.BLACK, 10 * x, 4 * x, 11 * x, 5 * x);
    private CustomRect outline91 = new CustomRect("Outline", Color.BLACK, 10 * x, 25 * x, 11 * x, 26 * x);
    private CustomRect outline92 = new CustomRect("Outline", Color.BLACK, 10 * x, 32 * x, 11 * x, 33 * x);
    private CustomRect outline93 = new CustomRect("Outline", Color.BLACK, 10 * x, 35 * x, 11 * x, 36 * x);
    private CustomRect outline94 = new CustomRect("Outline", Color.BLACK, 11 * x, 5 * x, 12 * x, 6 * x);
    private CustomRect outline95 = new CustomRect("Outline", Color.BLACK, 11 * x, 8 * x, 12 * x, 9 * x);
    private CustomRect outline96 = new CustomRect("Outline", Color.BLACK, 11 * x, 26 * x, 12 * x, 27 * x);
    private CustomRect outline97 = new CustomRect("Outline", Color.BLACK, 11 * x, 30 * x, 12 * x, 31 * x);
    private CustomRect outline98 = new CustomRect("Outline", Color.BLACK, 11 * x, 31 * x, 12 * x, 32 * x);
    private CustomRect outline99 = new CustomRect("Outline", Color.BLACK, 11 * x, 35 * x, 12 * x, 36 * x);
    private CustomRect outline100 = new CustomRect("Outline", Color.BLACK, 12 * x, 6 * x, 13 * x, 7 * x);
    private CustomRect outline101 = new CustomRect("Outline", Color.BLACK, 12 * x, 8 * x, 13 * x, 9 * x);
    private CustomRect outline102 = new CustomRect("Outline", Color.BLACK, 12 * x, 27 * x, 13 * x, 28 * x);
    private CustomRect outline103 = new CustomRect("Outline", Color.BLACK, 12 * x, 28 * x, 13 * x, 29 * x);
    private CustomRect outline104 = new CustomRect("Outline", Color.BLACK, 12 * x, 29 * x, 13 * x, 30 * x);
    private CustomRect outline105 = new CustomRect("Outline", Color.BLACK, 12 * x, 36 * x, 13 * x, 37 * x);
    private CustomRect outline106 = new CustomRect("Outline", Color.BLACK, 13 * x, 7 * x, 14 * x, 8 * x);
    private CustomRect outline107 = new CustomRect("Outline", Color.BLACK, 13 * x, 36 * x, 14 * x, 37 * x);
    private CustomRect outline108 = new CustomRect("Outline", Color.BLACK, 14 * x, 7 * x, 15 * x, 8 * x);
    private CustomRect outline109 = new CustomRect("Outline", Color.BLACK, 14 * x, 36 * x, 15 * x, 37 * x);
    private CustomRect outline110 = new CustomRect("Outline", Color.BLACK, 15 * x, 6 * x, 16 * x, 7 * x);
    private CustomRect outline111 = new CustomRect("Outline", Color.BLACK, 15 * x, 26 * x, 16 * x, 27 * x);
    private CustomRect outline112 = new CustomRect("Outline", Color.BLACK, 15 * x, 37 * x, 16 * x, 38 * x);
    private CustomRect outline113 = new CustomRect("Outline", Color.BLACK, 16 * x, 6 * x, 17 * x, 7 * x);
    private CustomRect outline114 = new CustomRect("Outline", Color.BLACK, 16 * x, 27 * x, 17 * x, 28 * x);
    private CustomRect outline115 = new CustomRect("Outline", Color.BLACK, 16 * x, 37 * x, 17 * x, 38 * x);
    private CustomRect outline116 = new CustomRect("Outline", Color.BLACK, 17 * x, 6 * x, 18 * x, 7 * x);
    private CustomRect outline117 = new CustomRect("Outline", Color.BLACK, 17 * x, 27 * x, 18 * x, 28 * x);
    private CustomRect outline118 = new CustomRect("Outline", Color.BLACK, 17 * x, 28 * x, 18 * x, 29 * x);
    private CustomRect outline119 = new CustomRect("Outline", Color.BLACK, 17 * x, 29 * x, 18 * x, 30 * x);
    private CustomRect outline120 = new CustomRect("Outline", Color.BLACK, 17 * x, 30 * x, 18 * x, 31 * x);
    private CustomRect outline121 = new CustomRect("Outline", Color.BLACK, 17 * x, 31 * x, 18 * x, 32 * x);
    private CustomRect outline122 = new CustomRect("Outline", Color.BLACK, 17 * x, 37 * x, 18 * x, 38 * x);
    private CustomRect outline123 = new CustomRect("Outline", Color.BLACK, 18 * x, 6 * x, 19 * x, 7 * x);
    private CustomRect outline124 = new CustomRect("Outline", Color.BLACK, 18 * x, 27 * x, 19 * x, 28 * x);
    private CustomRect outline125 = new CustomRect("Outline", Color.BLACK, 18 * x, 32 * x, 19 * x, 33 * x);
    private CustomRect outline126 = new CustomRect("Outline", Color.BLACK, 18 * x, 37 * x, 19 * x, 38 * x);
    private CustomRect outline127 = new CustomRect("Outline", Color.BLACK, 19 * x, 6 * x, 20 * x, 7 * x);
    private CustomRect outline128 = new CustomRect("Outline", Color.BLACK, 19 * x, 23 * x, 20 * x, 24 * x);
    private CustomRect outline129 = new CustomRect("Outline", Color.BLACK, 19 * x, 27 * x, 20 * x, 28 * x);
    private CustomRect outline130 = new CustomRect("Outline", Color.BLACK, 19 * x, 33 * x, 20 * x, 34 * x);
    private CustomRect outline131 = new CustomRect("Outline", Color.BLACK, 19 * x, 37 * x, 20 * x, 38 * x);
    private CustomRect outline132 = new CustomRect("Outline", Color.BLACK, 20 * x, 6 * x, 21 * x, 7 * x);
    private CustomRect outline133 = new CustomRect("Outline", Color.BLACK, 20 * x, 23 * x, 21 * x, 24 * x);
    private CustomRect outline134 = new CustomRect("Outline", Color.BLACK, 20 * x, 24 * x, 21 * x, 25 * x);
    private CustomRect outline135 = new CustomRect("Outline", Color.BLACK, 20 * x, 26 * x, 21 * x, 27 * x);
    private CustomRect outline136 = new CustomRect("Outline", Color.BLACK, 20 * x, 34 * x, 21 * x, 35 * x);
    private CustomRect outline137 = new CustomRect("Outline", Color.BLACK, 20 * x, 37 * x, 21 * x, 38 * x);
    private CustomRect outline138 = new CustomRect("Outline", Color.BLACK, 39 * x, 0 * x, 40 * x, 1 * x);
    private CustomRect outline139 = new CustomRect("Outline", Color.BLACK, 39 * x, 1 * x, 40 * x, 2 * x);
    private CustomRect outline140 = new CustomRect("Outline", Color.BLACK, 39 * x, 2 * x, 40 * x, 3 * x);
    private CustomRect outline141 = new CustomRect("Outline", Color.BLACK, 39 * x, 3 * x, 40 * x, 4 * x);
    private CustomRect outline142 = new CustomRect("Outline", Color.BLACK, 39 * x, 4 * x, 40 * x, 5 * x);
    private CustomRect outline143 = new CustomRect("Outline", Color.BLACK, 39 * x, 5 * x, 40 * x, 6 * x);
    private CustomRect outline144 = new CustomRect("Outline", Color.BLACK, 38 * x, 0 * x, 39 * x, 1 * x);
    private CustomRect outline145 = new CustomRect("Outline", Color.BLACK, 38 * x, 1 * x, 39 * x, 2 * x);
    private CustomRect outline146 = new CustomRect("Outline", Color.BLACK, 38 * x, 2 * x, 39 * x, 3 * x);
    private CustomRect outline147 = new CustomRect("Outline", Color.BLACK, 38 * x, 3 * x, 39 * x, 4 * x);
    private CustomRect outline148 = new CustomRect("Outline", Color.BLACK, 38 * x, 4 * x, 39 * x, 5 * x);
    private CustomRect outline149 = new CustomRect("Outline", Color.BLACK, 38 * x, 5 * x, 39 * x, 6 * x);
    private CustomRect outline150 = new CustomRect("Outline", Color.BLACK, 38 * x, 6 * x, 39 * x, 7 * x);
    private CustomRect outline151 = new CustomRect("Outline", Color.BLACK, 38 * x, 7 * x, 39 * x, 8 * x);
    private CustomRect outline152 = new CustomRect("Outline", Color.BLACK, 37 * x, 0 * x, 38 * x, 1 * x);
    private CustomRect outline153 = new CustomRect("Outline", Color.BLACK, 37 * x, 1 * x, 38 * x, 2 * x);
    private CustomRect outline154 = new CustomRect("Outline", Color.BLACK, 37 * x, 2 * x, 38 * x, 3 * x);
    private CustomRect outline155 = new CustomRect("Outline", Color.BLACK, 37 * x, 3 * x, 38 * x, 4 * x);
    private CustomRect outline156 = new CustomRect("Outline", Color.BLACK, 37 * x, 4 * x, 38 * x, 5 * x);
    private CustomRect outline157 = new CustomRect("Outline", Color.BLACK, 37 * x, 5 * x, 38 * x, 6 * x);
    private CustomRect outline158 = new CustomRect("Outline", Color.BLACK, 37 * x, 6 * x, 38 * x, 7 * x);
    private CustomRect outline159 = new CustomRect("Outline", Color.BLACK, 37 * x, 7 * x, 38 * x, 8 * x);
    private CustomRect outline160 = new CustomRect("Outline", Color.BLACK, 37 * x, 8 * x, 38 * x, 9 * x);
    private CustomRect outline161 = new CustomRect("Outline", Color.BLACK, 37 * x, 9 * x, 38 * x, 10 * x);
    private CustomRect outline162 = new CustomRect("Outline", Color.BLACK, 36 * x, 0 * x, 37 * x, 1 * x);
    private CustomRect outline163 = new CustomRect("Outline", Color.BLACK, 36 * x, 1 * x, 37 * x, 2 * x);
    private CustomRect outline164 = new CustomRect("Outline", Color.BLACK, 36 * x, 2 * x, 37 * x, 3 * x);
    private CustomRect outline165 = new CustomRect("Outline", Color.BLACK, 36 * x, 3 * x, 37 * x, 4 * x);
    private CustomRect outline166 = new CustomRect("Outline", Color.BLACK, 36 * x, 4 * x, 37 * x, 5 * x);
    private CustomRect outline167 = new CustomRect("Outline", Color.BLACK, 36 * x, 5 * x, 37 * x, 6 * x);
    private CustomRect outline168 = new CustomRect("Outline", Color.BLACK, 36 * x, 6 * x, 37 * x, 7 * x);
    private CustomRect outline169 = new CustomRect("Outline", Color.BLACK, 36 * x, 7 * x, 37 * x, 8 * x);
    private CustomRect outline170 = new CustomRect("Outline", Color.BLACK, 36 * x, 8 * x, 37 * x, 9 * x);
    private CustomRect outline171 = new CustomRect("Outline", Color.BLACK, 36 * x, 9 * x, 37 * x, 10 * x);
    private CustomRect outline172 = new CustomRect("Outline", Color.BLACK, 36 * x, 10 * x, 37 * x, 11 * x);
    private CustomRect outline173 = new CustomRect("Outline", Color.BLACK, 35 * x, 1 * x, 36 * x, 2 * x);
    private CustomRect outline174 = new CustomRect("Outline", Color.BLACK, 35 * x, 2 * x, 36 * x, 3 * x);
    private CustomRect outline175 = new CustomRect("Outline", Color.BLACK, 35 * x, 3 * x, 36 * x, 4 * x);
    private CustomRect outline176 = new CustomRect("Outline", Color.BLACK, 35 * x, 4 * x, 36 * x, 5 * x);
    private CustomRect outline177 = new CustomRect("Outline", Color.BLACK, 35 * x, 5 * x, 36 * x, 6 * x);
    private CustomRect outline178 = new CustomRect("Outline", Color.BLACK, 35 * x, 6 * x, 36 * x, 7 * x);
    private CustomRect outline179 = new CustomRect("Outline", Color.BLACK, 35 * x, 7 * x, 36 * x, 8 * x);
    private CustomRect outline180 = new CustomRect("Outline", Color.BLACK, 35 * x, 8 * x, 36 * x, 9 * x);
    private CustomRect outline181 = new CustomRect("Outline", Color.BLACK, 35 * x, 9 * x, 36 * x, 10 * x);
    private CustomRect outline182 = new CustomRect("Outline", Color.BLACK, 35 * x, 10 * x, 36 * x, 11 * x);
    private CustomRect outline183 = new CustomRect("Outline", Color.BLACK, 35 * x, 11 * x, 36 * x, 12 * x);
    private CustomRect outline184 = new CustomRect("Outline", Color.BLACK, 35 * x, 24 * x, 36 * x, 25 * x);
    private CustomRect outline185 = new CustomRect("Outline", Color.BLACK, 35 * x, 25 * x, 36 * x, 26 * x);
    private CustomRect outline186 = new CustomRect("Outline", Color.BLACK, 35 * x, 26 * x, 36 * x, 27 * x);
    private CustomRect outline187 = new CustomRect("Outline", Color.BLACK, 35 * x, 27 * x, 36 * x, 28 * x);
    private CustomRect outline188 = new CustomRect("Outline", Color.BLACK, 35 * x, 28 * x, 36 * x, 29 * x);
    private CustomRect outline189 = new CustomRect("Outline", Color.BLACK, 35 * x, 29 * x, 36 * x, 30 * x);
    private CustomRect outline190 = new CustomRect("Outline", Color.BLACK, 35 * x, 30 * x, 36 * x, 31 * x);
    private CustomRect outline191 = new CustomRect("Outline", Color.BLACK, 34 * x, 1 * x, 35 * x, 2 * x);
    private CustomRect outline192 = new CustomRect("Outline", Color.BLACK, 34 * x, 2 * x, 35 * x, 3 * x);
    private CustomRect outline193 = new CustomRect("Outline", Color.BLACK, 34 * x, 3 * x, 35 * x, 4 * x);
    private CustomRect outline194 = new CustomRect("Outline", Color.BLACK, 34 * x, 4 * x, 35 * x, 5 * x);
    private CustomRect outline195 = new CustomRect("Outline", Color.BLACK, 34 * x, 12 * x, 35 * x, 13 * x);
    private CustomRect outline196 = new CustomRect("Outline", Color.BLACK, 34 * x, 15 * x, 35 * x, 16 * x);
    private CustomRect outline197 = new CustomRect("Outline", Color.BLACK, 34 * x, 16 * x, 35 * x, 17 * x);
    private CustomRect outline198 = new CustomRect("Outline", Color.BLACK, 34 * x, 17 * x, 35 * x, 18 * x);
    private CustomRect outline199 = new CustomRect("Outline", Color.BLACK, 34 * x, 18 * x, 35 * x, 19 * x);
    private CustomRect outline200 = new CustomRect("Outline", Color.BLACK, 34 * x, 19 * x, 35 * x, 20 * x);
    private CustomRect outline201 = new CustomRect("Outline", Color.BLACK, 34 * x, 20 * x, 35 * x, 21 * x);
    private CustomRect outline202 = new CustomRect("Outline", Color.BLACK, 34 * x, 21 * x, 35 * x, 22 * x);
    private CustomRect outline203 = new CustomRect("Outline", Color.BLACK, 34 * x, 22 * x, 35 * x, 23 * x);
    private CustomRect outline204 = new CustomRect("Outline", Color.BLACK, 34 * x, 23 * x, 35 * x, 24 * x);
    private CustomRect outline205 = new CustomRect("Outline", Color.BLACK, 34 * x, 26 * x, 35 * x, 27 * x);
    private CustomRect outline206 = new CustomRect("Outline", Color.BLACK, 34 * x, 31 * x, 35 * x, 32 * x);
    private CustomRect outline207 = new CustomRect("Outline", Color.BLACK, 33 * x, 1 * x, 34 * x, 2 * x);
    private CustomRect outline208 = new CustomRect("Outline", Color.BLACK, 33 * x, 2 * x, 34 * x, 3 * x);
    private CustomRect outline209 = new CustomRect("Outline", Color.BLACK, 33 * x, 12 * x, 34 * x, 13 * x);
    private CustomRect outline210 = new CustomRect("Outline", Color.BLACK, 33 * x, 13 * x, 34 * x, 14 * x);
    private CustomRect outline211 = new CustomRect("Outline", Color.BLACK, 33 * x, 14 * x, 34 * x, 15 * x);
    private CustomRect outline212 = new CustomRect("Outline", Color.BLACK, 33 * x, 25 * x, 34 * x, 26 * x);
    private CustomRect outline213 = new CustomRect("Outline", Color.BLACK, 33 * x, 32 * x, 34 * x, 33 * x);
    private CustomRect outline214 = new CustomRect("Outline", Color.BLACK, 32 * x, 2 * x, 33 * x, 3 * x);
    private CustomRect outline215 = new CustomRect("Outline", Color.BLACK, 32 * x, 12 * x, 33 * x, 13 * x);
    private CustomRect outline216 = new CustomRect("Outline", Color.BLACK, 32 * x, 25 * x, 33 * x, 26 * x);
    private CustomRect outline217 = new CustomRect("Outline", Color.BLACK, 32 * x, 32 * x, 33 * x, 33 * x);
    private CustomRect outline218 = new CustomRect("Outline", Color.BLACK, 32 * x, 33 * x, 33 * x, 34 * x);
    private CustomRect outline219 = new CustomRect("Outline", Color.BLACK, 31 * x, 2 * x, 32 * x, 3 * x);
    private CustomRect outline220 = new CustomRect("Outline", Color.BLACK, 31 * x, 11 * x, 32 * x, 12 * x);
    private CustomRect outline221 = new CustomRect("Outline", Color.BLACK, 31 * x, 25 * x, 32 * x, 26 * x);
    private CustomRect outline222 = new CustomRect("Outline", Color.BLACK, 31 * x, 32 * x, 32 * x, 33 * x);
    private CustomRect outline223 = new CustomRect("Outline", Color.BLACK, 31 * x, 34 * x, 32 * x, 35 * x);
    private CustomRect outline224 = new CustomRect("Outline", Color.BLACK, 30 * x, 3 * x, 31 * x, 4 * x);
    private CustomRect outline225 = new CustomRect("Outline", Color.BLACK, 30 * x, 25 * x, 31 * x, 26 * x);
    private CustomRect outline226 = new CustomRect("Outline", Color.BLACK, 30 * x, 32 * x, 31 * x, 33 * x);
    private CustomRect outline227 = new CustomRect("Outline", Color.BLACK, 30 * x, 34 * x, 31 * x, 35 * x);
    private CustomRect outline228 = new CustomRect("Outline", Color.BLACK, 29 * x, 4 * x, 30 * x, 5 * x);
    private CustomRect outline229 = new CustomRect("Outline", Color.BLACK, 29 * x, 25 * x, 30 * x, 26 * x);
    private CustomRect outline230 = new CustomRect("Outline", Color.BLACK, 29 * x, 32 * x, 30 * x, 33 * x);
    private CustomRect outline231 = new CustomRect("Outline", Color.BLACK, 29 * x, 35 * x, 30 * x, 36 * x);
    private CustomRect outline232 = new CustomRect("Outline", Color.BLACK, 28 * x, 5 * x, 29 * x, 6 * x);
    private CustomRect outline233 = new CustomRect("Outline", Color.BLACK, 28 * x, 8 * x, 29 * x, 9 * x);
    private CustomRect outline234 = new CustomRect("Outline", Color.BLACK, 28 * x, 26 * x, 29 * x, 27 * x);
    private CustomRect outline235 = new CustomRect("Outline", Color.BLACK, 28 * x, 30 * x, 29 * x, 31 * x);
    private CustomRect outline236 = new CustomRect("Outline", Color.BLACK, 28 * x, 31 * x, 29 * x, 32 * x);
    private CustomRect outline237 = new CustomRect("Outline", Color.BLACK, 28 * x, 35 * x, 29 * x, 36 * x);
    private CustomRect outline238 = new CustomRect("Outline", Color.BLACK, 27 * x, 6 * x, 28 * x, 7 * x);
    private CustomRect outline239 = new CustomRect("Outline", Color.BLACK, 27 * x, 8 * x, 28 * x, 9 * x);
    private CustomRect outline240 = new CustomRect("Outline", Color.BLACK, 27 * x, 27 * x, 28 * x, 28 * x);
    private CustomRect outline241 = new CustomRect("Outline", Color.BLACK, 27 * x, 28 * x, 28 * x, 29 * x);
    private CustomRect outline242 = new CustomRect("Outline", Color.BLACK, 27 * x, 29 * x, 28 * x, 30 * x);
    private CustomRect outline243 = new CustomRect("Outline", Color.BLACK, 27 * x, 36 * x, 28 * x, 37 * x);
    private CustomRect outline244 = new CustomRect("Outline", Color.BLACK, 26 * x, 7 * x, 27 * x, 8 * x);
    private CustomRect outline245 = new CustomRect("Outline", Color.BLACK, 26 * x, 36 * x, 27 * x, 37 * x);
    private CustomRect outline246 = new CustomRect("Outline", Color.BLACK, 25 * x, 7 * x, 26 * x, 8 * x);
    private CustomRect outline247 = new CustomRect("Outline", Color.BLACK, 25 * x, 36 * x, 26 * x, 37 * x);
    private CustomRect outline248 = new CustomRect("Outline", Color.BLACK, 24 * x, 6 * x, 25 * x, 7 * x);
    private CustomRect outline249 = new CustomRect("Outline", Color.BLACK, 24 * x, 26 * x, 25 * x, 27 * x);
    private CustomRect outline250 = new CustomRect("Outline", Color.BLACK, 24 * x, 37 * x, 25 * x, 38 * x);
    private CustomRect outline251 = new CustomRect("Outline", Color.BLACK, 23 * x, 6 * x, 24 * x, 7 * x);
    private CustomRect outline252 = new CustomRect("Outline", Color.BLACK, 23 * x, 27 * x, 24 * x, 28 * x);
    private CustomRect outline253 = new CustomRect("Outline", Color.BLACK, 23 * x, 37 * x, 24 * x, 38 * x);
    private CustomRect outline254 = new CustomRect("Outline", Color.BLACK, 22 * x, 6 * x, 23 * x, 7 * x);
    private CustomRect outline255 = new CustomRect("Outline", Color.BLACK, 22 * x, 27 * x, 23 * x, 28 * x);
    private CustomRect outline256 = new CustomRect("Outline", Color.BLACK, 22 * x, 28 * x, 23 * x, 29 * x);
    private CustomRect outline257 = new CustomRect("Outline", Color.BLACK, 22 * x, 29 * x, 23 * x, 30 * x);
    private CustomRect outline258 = new CustomRect("Outline", Color.BLACK, 22 * x, 30 * x, 23 * x, 31 * x);
    private CustomRect outline259 = new CustomRect("Outline", Color.BLACK, 22 * x, 31 * x, 23 * x, 32 * x);
    private CustomRect outline260 = new CustomRect("Outline", Color.BLACK, 22 * x, 37 * x, 23 * x, 38 * x);
    private CustomRect outline261 = new CustomRect("Outline", Color.BLACK, 21 * x, 6 * x, 22 * x, 7 * x);
    private CustomRect outline262 = new CustomRect("Outline", Color.BLACK, 21 * x, 27 * x, 22 * x, 28 * x);
    private CustomRect outline263 = new CustomRect("Outline", Color.BLACK, 21 * x, 32 * x, 22 * x, 33 * x);
    private CustomRect outline264 = new CustomRect("Outline", Color.BLACK, 21 * x, 37 * x, 22 * x, 38 * x);
    private CustomRect outline265 = new CustomRect("Outline", Color.BLACK, 21 * x, 6 * x, 22 * x, 7 * x);
    private CustomRect outline266 = new CustomRect("Outline", Color.BLACK, 21 * x, 23 * x, 22 * x, 24 * x);
    private CustomRect outline267 = new CustomRect("Outline", Color.BLACK, 21 * x, 27 * x, 22 * x, 28 * x);
    private CustomRect outline268 = new CustomRect("Outline", Color.BLACK, 21 * x, 33 * x, 22 * x, 34 * x);
    private CustomRect outline269 = new CustomRect("Outline", Color.BLACK, 21 * x, 37 * x, 22 * x, 38 * x);

    private CustomRect leftCheek0 = new CustomRect("Left Cheek", Color.RED, 5*x, 27*x, 6*x, 28*x);
    private CustomRect leftCheek1 = new CustomRect("Left Cheek", Color.RED, 5*x, 28*x, 6*x, 29*x);
    private CustomRect leftCheek2 = new CustomRect("Left Cheek", Color.RED, 5*x, 29*x, 6*x, 30*x);
    private CustomRect leftCheek3 = new CustomRect("Left Cheek", Color.RED, 5*x, 30*x, 6*x, 31*x);
    private CustomRect leftCheek4 = new CustomRect("Left Cheek", Color.RED, 6*x, 26*x, 7*x, 27*x);
    private CustomRect leftCheek5 = new CustomRect("Left Cheek", Color.RED, 6*x, 27*x, 7*x, 28*x);
    private CustomRect leftCheek6 = new CustomRect("Left Cheek", Color.RED, 6*x, 28*x, 7*x, 29*x);
    private CustomRect leftCheek7 = new CustomRect("Left Cheek", Color.RED, 6*x, 29*x, 7*x, 30*x);
    private CustomRect leftCheek8 = new CustomRect("Left Cheek", Color.RED, 6*x, 30*x, 7*x, 31*x);
    private CustomRect leftCheek9 = new CustomRect("Left Cheek", Color.RED, 6*x, 31*x, 7*x, 32*x);
    private CustomRect leftCheek10 = new CustomRect("Left Cheek", Color.RED, 7*x, 26*x, 8*x, 27*x);
    private CustomRect leftCheek11 = new CustomRect("Left Cheek", Color.RED, 7*x, 27*x, 8*x, 28*x);
    private CustomRect leftCheek12 = new CustomRect("Left Cheek", Color.RED, 7*x, 28*x, 8*x, 29*x);
    private CustomRect leftCheek13 = new CustomRect("Left Cheek", Color.RED, 7*x, 29*x, 8*x, 30*x);
    private CustomRect leftCheek14 = new CustomRect("Left Cheek", Color.RED, 7*x, 30*x, 8*x, 31*x);
    private CustomRect leftCheek15 = new CustomRect("Left Cheek", Color.RED, 7*x, 31*x, 8*x, 32*x);
    private CustomRect leftCheek16 = new CustomRect("Left Cheek", Color.RED, 8*x, 26*x, 9*x, 27*x);
    private CustomRect leftCheek17 = new CustomRect("Left Cheek", Color.RED, 8*x, 27*x, 9*x, 28*x);
    private CustomRect leftCheek18 = new CustomRect("Left Cheek", Color.RED, 8*x, 28*x, 9*x, 29*x);
    private CustomRect leftCheek19 = new CustomRect("Left Cheek", Color.RED, 8*x, 29*x, 9*x, 30*x);
    private CustomRect leftCheek20 = new CustomRect("Left Cheek", Color.RED, 8*x, 30*x, 9*x, 31*x);
    private CustomRect leftCheek21 = new CustomRect("Left Cheek", Color.RED, 8*x, 31*x, 9*x, 32*x);
    private CustomRect leftCheek22 = new CustomRect("Left Cheek", Color.RED, 9*x, 26*x, 10*x, 27*x);
    private CustomRect leftCheek23 = new CustomRect("Left Cheek", Color.RED, 9*x, 27*x, 10*x, 28*x);
    private CustomRect leftCheek24 = new CustomRect("Left Cheek", Color.RED, 9*x, 28*x, 10*x, 29*x);
    private CustomRect leftCheek25 = new CustomRect("Left Cheek", Color.RED, 9*x, 29*x, 10*x, 30*x);
    private CustomRect leftCheek26 = new CustomRect("Left Cheek", Color.RED, 9*x, 30*x, 10*x, 31*x);
    private CustomRect leftCheek27 = new CustomRect("Left Cheek", Color.RED, 9*x, 31*x, 10*x, 32*x);
    private CustomRect leftCheek28 = new CustomRect("Left Cheek", Color.RED, 10*x, 26*x, 11*x, 27*x);
    private CustomRect leftCheek29 = new CustomRect("Left Cheek", Color.RED, 10*x, 27*x, 11*x, 28*x);
    private CustomRect leftCheek30 = new CustomRect("Left Cheek", Color.RED, 10*x, 28*x, 11*x, 29*x);
    private CustomRect leftCheek31 = new CustomRect("Left Cheek", Color.RED, 10*x, 29*x, 11*x, 30*x);
    private CustomRect leftCheek32 = new CustomRect("Left Cheek", Color.RED, 10*x, 30*x, 11*x, 31*x);
    private CustomRect leftCheek33 = new CustomRect("Left Cheek", Color.RED, 10*x, 31*x, 11*x, 32*x);
    private CustomRect leftCheek34 = new CustomRect("Left Cheek", Color.RED, 11*x, 27*x, 12*x, 28*x);
    private CustomRect leftCheek35 = new CustomRect("Left Cheek", Color.RED, 11*x, 28*x, 12*x, 29*x);
    private CustomRect leftCheek36 = new CustomRect("Left Cheek", Color.RED, 11*x, 29*x, 12*x, 30*x);

    private CustomRect rightCheek0 = new CustomRect("Right Cheek", Color.RED, 28*x, 27*x, 29*x, 28*x);
    private CustomRect rightCheek1 = new CustomRect("Right Cheek", Color.RED, 28*x, 28*x, 29*x, 29*x);
    private CustomRect rightCheek2 = new CustomRect("Right Cheek", Color.RED, 28*x, 29*x, 29*x, 30*x);
    private CustomRect rightCheek3 = new CustomRect("Right Cheek", Color.RED, 29*x, 26*x, 30*x, 27*x);
    private CustomRect rightCheek4 = new CustomRect("Right Cheek", Color.RED, 29*x, 27*x, 30*x, 28*x);
    private CustomRect rightCheek5 = new CustomRect("Right Cheek", Color.RED, 29*x, 28*x, 30*x, 29*x);
    private CustomRect rightCheek6 = new CustomRect("Right Cheek", Color.RED, 29*x, 29*x, 30*x, 30*x);
    private CustomRect rightCheek7 = new CustomRect("Right Cheek", Color.RED, 29*x, 30*x, 30*x, 31*x);
    private CustomRect rightCheek8 = new CustomRect("Right Cheek", Color.RED, 29*x, 31*x, 30*x, 32*x);
    private CustomRect rightCheek9 = new CustomRect("Right Cheek", Color.RED, 30*x, 26*x, 31*x, 27*x);
    private CustomRect rightCheek10 = new CustomRect("Right Cheek", Color.RED, 30*x, 27*x, 31*x, 28*x);
    private CustomRect rightCheek11 = new CustomRect("Right Cheek", Color.RED, 30*x, 28*x, 31*x, 29*x);
    private CustomRect rightCheek12 = new CustomRect("Right Cheek", Color.RED, 30*x, 29*x, 31*x, 30*x);
    private CustomRect rightCheek13 = new CustomRect("Right Cheek", Color.RED, 30*x, 30*x, 31*x, 31*x);
    private CustomRect rightCheek14 = new CustomRect("Right Cheek", Color.RED, 30*x, 31*x, 31*x, 32*x);
    private CustomRect rightCheek15 = new CustomRect("Right Cheek", Color.RED, 31*x, 26*x, 32*x, 27*x);
    private CustomRect rightCheek16 = new CustomRect("Right Cheek", Color.RED, 31*x, 27*x, 32*x, 28*x);
    private CustomRect rightCheek17 = new CustomRect("Right Cheek", Color.RED, 31*x, 28*x, 32*x, 29*x);
    private CustomRect rightCheek18 = new CustomRect("Right Cheek", Color.RED, 31*x, 29*x, 32*x, 30*x);
    private CustomRect rightCheek19 = new CustomRect("Right Cheek", Color.RED, 31*x, 30*x, 32*x, 31*x);
    private CustomRect rightCheek20 = new CustomRect("Right Cheek", Color.RED, 31*x, 31*x, 32*x, 32*x);
    private CustomRect rightCheek21 = new CustomRect("Right Cheek", Color.RED, 32*x, 26*x, 33*x, 27*x);
    private CustomRect rightCheek22 = new CustomRect("Right Cheek", Color.RED, 32*x, 27*x, 33*x, 28*x);
    private CustomRect rightCheek23 = new CustomRect("Right Cheek", Color.RED, 32*x, 28*x, 33*x, 29*x);
    private CustomRect rightCheek24 = new CustomRect("Right Cheek", Color.RED, 32*x, 29*x, 33*x, 30*x);
    private CustomRect rightCheek25 = new CustomRect("Right Cheek", Color.RED, 32*x, 30*x, 33*x, 31*x);
    private CustomRect rightCheek26 = new CustomRect("Right Cheek", Color.RED, 32*x, 31*x, 33*x, 32*x);
    private CustomRect rightCheek27 = new CustomRect("Right Cheek", Color.RED, 33*x, 26*x, 34*x, 27*x);
    private CustomRect rightCheek28 = new CustomRect("Right Cheek", Color.RED, 33*x, 27*x, 34*x, 28*x);
    private CustomRect rightCheek29 = new CustomRect("Right Cheek", Color.RED, 33*x, 28*x, 34*x, 29*x);
    private CustomRect rightCheek30 = new CustomRect("Right Cheek", Color.RED, 33*x, 29*x, 34*x, 30*x);
    private CustomRect rightCheek31 = new CustomRect("Right Cheek", Color.RED, 33*x, 30*x, 34*x, 31*x);
    private CustomRect rightCheek32 = new CustomRect("Right Cheek", Color.RED, 33*x, 31*x, 34*x, 32*x);
    private CustomRect rightCheek33 = new CustomRect("Right Cheek", Color.RED, 34*x, 27*x, 35*x, 28*x);
    private CustomRect rightCheek34 = new CustomRect("Right Cheek", Color.RED, 34*x, 28*x, 35*x, 29*x);
    private CustomRect rightCheek35 = new CustomRect("Right Cheek", Color.RED, 34*x, 29*x, 35*x, 30*x);
    private CustomRect rightCheek36 = new CustomRect("Right Cheek", Color.RED, 34*x, 30*x, 35*x, 31*x);

    private CustomRect leftEye0 = new CustomRect("Left Eye", Color.BLACK, 8*x, 19*x, 9*x, 20*x);
    private CustomRect leftEye1 = new CustomRect("Left Eye", Color.BLACK, 8*x, 20*x, 9*x, 21*x);
    private CustomRect leftEye2 = new CustomRect("Left Eye", Color.BLACK, 8*x, 21*x, 9*x, 22*x);
    private CustomRect leftEye3 = new CustomRect("Left Eye", Color.BLACK, 8*x, 22*x, 9*x, 23*x);
    private CustomRect leftEye4 = new CustomRect("Left Eye", Color.BLACK, 9*x, 18*x, 10*x, 19*x);
    private CustomRect leftEye5 = new CustomRect("Left Eye", Color.BLACK, 9*x, 19*x, 10*x, 20*x);
    private CustomRect leftEye6 = new CustomRect("Left Eye", Color.BLACK, 9*x, 20*x, 10*x, 21*x);
    private CustomRect leftEye7 = new CustomRect("Left Eye", Color.BLACK, 9*x, 21*x, 10*x, 22*x);
    private CustomRect leftEye8 = new CustomRect("Left Eye", Color.BLACK, 9*x, 22*x, 10*x, 23*x);
    private CustomRect leftEye9 = new CustomRect("Left Eye", Color.BLACK, 9*x, 23*x, 10*x, 24*x);
    private CustomRect leftEye10 = new CustomRect("Left Eye", Color.BLACK, 10*x, 17*x, 11*x, 18*x);
    private CustomRect leftEye11 = new CustomRect("Left Eye", Color.BLACK, 10*x, 18*x, 11*x, 19*x);
    private CustomRect leftEye12 = new CustomRect("Left Eye", Color.BLACK, 10*x, 19*x, 11*x, 20*x);
    private CustomRect leftEye13 = new CustomRect("Left Eye", Color.BLACK, 10*x, 20*x, 11*x, 21*x);
    private CustomRect leftEye14 = new CustomRect("Left Eye", Color.BLACK, 10*x, 21*x, 11*x, 22*x);
    private CustomRect leftEye15 = new CustomRect("Left Eye", Color.BLACK, 10*x, 22*x, 11*x, 23*x);
    private CustomRect leftEye16 = new CustomRect("Left Eye", Color.BLACK, 10*x, 23*x, 11*x, 24*x);
    private CustomRect leftEye17 = new CustomRect("Left Eye", Color.BLACK, 11*x, 17*x, 12*x, 18*x);
    private CustomRect leftEye18 = new CustomRect("Left Eye", Color.BLACK, 11*x, 18*x, 12*x, 19*x);
    private CustomRect leftEye19 = new CustomRect("Left Eye", Color.BLACK, 11*x, 20*x, 12*x, 21*x);
    private CustomRect leftEye20 = new CustomRect("Left Eye", Color.BLACK, 11*x, 21*x, 12*x, 22*x);
    private CustomRect leftEye21 = new CustomRect("Left Eye", Color.BLACK, 11*x, 22*x, 12*x, 23*x);
    private CustomRect leftEye22 = new CustomRect("Left Eye", Color.BLACK, 11*x, 23*x, 12*x, 24*x);
    private CustomRect leftEye23 = new CustomRect("Left Eye", Color.BLACK, 12*x, 17*x, 13*x, 18*x);
    private CustomRect leftEye24 = new CustomRect("Left Eye", Color.BLACK, 12*x, 21*x, 13*x, 22*x);
    private CustomRect leftEye25 = new CustomRect("Left Eye", Color.BLACK, 12*x, 22*x, 13*x, 23*x);
    private CustomRect leftEye26 = new CustomRect("Left Eye", Color.BLACK, 12*x, 23*x, 13*x, 24*x);
    private CustomRect leftEye27 = new CustomRect("Left Eye", Color.BLACK, 13*x, 17*x, 14*x, 18*x);
    private CustomRect leftEye28 = new CustomRect("Left Eye", Color.BLACK, 13*x, 18*x, 14*x, 19*x);
    private CustomRect leftEye29 = new CustomRect("Left Eye", Color.BLACK, 13*x, 21*x, 14*x, 22*x);
    private CustomRect leftEye30 = new CustomRect("Left Eye", Color.BLACK, 13*x, 22*x, 14*x, 23*x);
    private CustomRect leftEye31 = new CustomRect("Left Eye", Color.BLACK, 13*x, 23*x, 14*x, 24*x);
    private CustomRect leftEye32 = new CustomRect("Left Eye", Color.BLACK, 14*x, 18*x, 15*x, 19*x);
    private CustomRect leftEye33 = new CustomRect("Left Eye", Color.BLACK, 14*x, 19*x, 15*x, 20*x);
    private CustomRect leftEye34 = new CustomRect("Left Eye", Color.BLACK, 14*x, 20*x, 15*x, 21*x);
    private CustomRect leftEye35 = new CustomRect("Left Eye", Color.BLACK, 14*x, 21*x, 15*x, 22*x);
    private CustomRect leftEye36 = new CustomRect("Left Eye", Color.BLACK, 14*x, 22*x, 15*x, 23*x);

    private CustomRect rightEye0 = new CustomRect("Right Eye", Color.BLACK, 25*x, 18*x, 26*x, 19*x);
    private CustomRect rightEye1 = new CustomRect("Right Eye", Color.BLACK, 25*x, 19*x, 26*x, 20*x);
    private CustomRect rightEye2 = new CustomRect("Right Eye", Color.BLACK, 25*x, 20*x, 26*x, 21*x);
    private CustomRect rightEye3 = new CustomRect("Right Eye", Color.BLACK, 25*x, 21*x, 26*x, 22*x);
    private CustomRect rightEye4 = new CustomRect("Right Eye", Color.BLACK, 25*x, 22*x, 26*x, 23*x);
    private CustomRect rightEye5 = new CustomRect("Right Eye", Color.BLACK, 26*x, 17*x, 27*x, 18*x);
    private CustomRect rightEye6 = new CustomRect("Right Eye", Color.BLACK, 26*x, 18*x, 27*x, 19*x);
    private CustomRect rightEye7 = new CustomRect("Right Eye", Color.BLACK, 26*x, 21*x, 27*x, 22*x);
    private CustomRect rightEye8 = new CustomRect("Right Eye", Color.BLACK, 26*x, 22*x, 27*x, 23*x);
    private CustomRect rightEye9 = new CustomRect("Right Eye", Color.BLACK, 26*x, 23*x, 27*x, 24*x);
    private CustomRect rightEye10 = new CustomRect("Right Eye", Color.BLACK, 27*x, 17*x, 28*x, 18*x);
    private CustomRect rightEye11 = new CustomRect("Right Eye", Color.BLACK, 27*x, 21*x, 28*x, 22*x);
    private CustomRect rightEye12 = new CustomRect("Right Eye", Color.BLACK, 27*x, 22*x, 28*x, 23*x);
    private CustomRect rightEye13 = new CustomRect("Right Eye", Color.BLACK, 27*x, 23*x, 28*x, 24*x);
    private CustomRect rightEye14 = new CustomRect("Right Eye", Color.BLACK, 28*x, 17*x, 29*x, 18*x);
    private CustomRect rightEye15 = new CustomRect("Right Eye", Color.BLACK, 28*x, 18*x, 29*x, 19*x);
    private CustomRect rightEye16 = new CustomRect("Right Eye", Color.BLACK, 28*x, 20*x, 29*x, 21*x);
    private CustomRect rightEye17 = new CustomRect("Right Eye", Color.BLACK, 28*x, 21*x, 29*x, 22*x);
    private CustomRect rightEye18 = new CustomRect("Right Eye", Color.BLACK, 28*x, 22*x, 29*x, 23*x);
    private CustomRect rightEye19 = new CustomRect("Right Eye", Color.BLACK, 28*x, 23*x, 29*x, 24*x);
    private CustomRect rightEye20 = new CustomRect("Right Eye", Color.BLACK, 29*x, 17*x, 30*x, 18*x);
    private CustomRect rightEye21 = new CustomRect("Right Eye", Color.BLACK, 29*x, 18*x, 30*x, 19*x);
    private CustomRect rightEye22 = new CustomRect("Right Eye", Color.BLACK, 29*x, 19*x, 30*x, 20*x);
    private CustomRect rightEye23 = new CustomRect("Right Eye", Color.BLACK, 29*x, 20*x, 30*x, 21*x);
    private CustomRect rightEye24 = new CustomRect("Right Eye", Color.BLACK, 29*x, 21*x, 30*x, 22*x);
    private CustomRect rightEye25 = new CustomRect("Right Eye", Color.BLACK, 29*x, 22*x, 30*x, 23*x);
    private CustomRect rightEye26 = new CustomRect("Right Eye", Color.BLACK, 29*x, 23*x, 30*x, 24*x);
    private CustomRect rightEye27 = new CustomRect("Right Eye", Color.BLACK, 30*x, 18*x, 31*x, 19*x);
    private CustomRect rightEye28 = new CustomRect("Right Eye", Color.BLACK, 30*x, 19*x, 31*x, 20*x);
    private CustomRect rightEye29 = new CustomRect("Right Eye", Color.BLACK, 30*x, 20*x, 31*x, 21*x);
    private CustomRect rightEye30 = new CustomRect("Right Eye", Color.BLACK, 30*x, 21*x, 31*x, 22*x);
    private CustomRect rightEye31 = new CustomRect("Right Eye", Color.BLACK, 30*x, 22*x, 31*x, 23*x);
    private CustomRect rightEye32 = new CustomRect("Right Eye", Color.BLACK, 30*x, 23*x, 31*x, 24*x);
    private CustomRect rightEye33 = new CustomRect("Right Eye", Color.BLACK, 31*x, 19*x, 32*x, 20*x);
    private CustomRect rightEye34 = new CustomRect("Right Eye", Color.BLACK, 31*x, 20*x, 32*x, 21*x);
    private CustomRect rightEye35 = new CustomRect("Right Eye", Color.BLACK, 31*x, 21*x, 32*x, 22*x);
    private CustomRect rightEye36 = new CustomRect("Right Eye", Color.BLACK, 31*x, 22*x, 32*x, 23*x);

    private CustomRect mouth0 = new CustomRect("Mouth", Color.RED, 18*x, 28*x, 19*x, 29*x);
    private CustomRect mouth1 = new CustomRect("Mouth", Color.RED, 18*x, 29*x, 19*x, 30*x);
    private CustomRect mouth2 = new CustomRect("Mouth", Color.RED, 18*x, 30*x, 19*x, 31*x);
    private CustomRect mouth3 = new CustomRect("Mouth", Color.RED, 18*x, 31*x, 19*x, 32*x);
    private CustomRect mouth4 = new CustomRect("Mouth", Color.RED, 19*x, 28*x, 20*x, 29*x);
    private CustomRect mouth5 = new CustomRect("Mouth", Color.RED, 19*x, 29*x, 20*x, 30*x);
    private CustomRect mouth6 = new CustomRect("Mouth", Color.RED, 19*x, 30*x, 20*x, 31*x);
    private CustomRect mouth7 = new CustomRect("Mouth", Color.RED, 19*x, 31*x, 20*x, 32*x);
    private CustomRect mouth8 = new CustomRect("Mouth", Color.RED, 19*x, 32*x, 20*x, 33*x);
    private CustomRect mouth9 = new CustomRect("Mouth", Color.RED, 20*x, 27*x, 21*x, 28*x);
    private CustomRect mouth10 = new CustomRect("Mouth", Color.RED, 20*x, 28*x, 21*x, 29*x);
    private CustomRect mouth11 = new CustomRect("Mouth", Color.RED, 20*x, 29*x, 21*x, 30*x);
    private CustomRect mouth12 = new CustomRect("Mouth", Color.RED, 20*x, 30*x, 21*x, 31*x);
    private CustomRect mouth13 = new CustomRect("Mouth", Color.RED, 20*x, 31*x, 21*x, 32*x);
    private CustomRect mouth14 = new CustomRect("Mouth", Color.RED, 20*x, 32*x, 21*x, 33*x);
    private CustomRect mouth15 = new CustomRect("Mouth", Color.RED, 20*x, 33*x, 21*x, 34*x);
    private CustomRect mouth16 = new CustomRect("Mouth", Color.RED, 21*x, 28*x, 22*x, 29*x);
    private CustomRect mouth17 = new CustomRect("Mouth", Color.RED, 21*x, 29*x, 22*x, 30*x);
    private CustomRect mouth18 = new CustomRect("Mouth", Color.RED, 21*x, 30*x, 22*x, 31*x);
    private CustomRect mouth19 = new CustomRect("Mouth", Color.RED, 21*x, 31*x, 22*x, 32*x);












    public ColorsCaboom(Context context) {
        super(context);
        setWillNotDraw(false);

    }

    public ColorsCaboom(Context context, AttributeSet attrs) {
        super(context, attrs);
        setWillNotDraw(false);
    }

    public ColorsCaboom(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        setWillNotDraw(false);
    }

    //draws every single CustomRect that I listed above
    @Override
    public void onDraw(Canvas canvas) {
        outline0.drawMe(canvas);
        outline1.drawMe(canvas);
        outline2.drawMe(canvas);
        outline3.drawMe(canvas);
        outline4.drawMe(canvas);
        outline5.drawMe(canvas);
        outline6.drawMe(canvas);
        outline7.drawMe(canvas);
        outline8.drawMe(canvas);
        outline9.drawMe(canvas);
        outline10.drawMe(canvas);
        outline11.drawMe(canvas);
        outline12.drawMe(canvas);
        outline13.drawMe(canvas);
        outline14.drawMe(canvas);
        outline15.drawMe(canvas);
        outline16.drawMe(canvas);
        outline17.drawMe(canvas);
        outline18.drawMe(canvas);
        outline19.drawMe(canvas);
        outline20.drawMe(canvas);
        outline21.drawMe(canvas);
        outline22.drawMe(canvas);
        outline23.drawMe(canvas);
        outline24.drawMe(canvas);
        outline25.drawMe(canvas);
        outline26.drawMe(canvas);
        outline27.drawMe(canvas);
        outline28.drawMe(canvas);
        outline29.drawMe(canvas);
        outline30.drawMe(canvas);
        outline31.drawMe(canvas);
        outline32.drawMe(canvas);
        outline33.drawMe(canvas);
        outline34.drawMe(canvas);
        outline35.drawMe(canvas);
        outline36.drawMe(canvas);
        outline37.drawMe(canvas);
        outline38.drawMe(canvas);
        outline39.drawMe(canvas);
        outline40.drawMe(canvas);
        outline41.drawMe(canvas);
        outline42.drawMe(canvas);
        outline43.drawMe(canvas);
        outline44.drawMe(canvas);
        outline45.drawMe(canvas);
        outline46.drawMe(canvas);
        outline47.drawMe(canvas);
        outline48.drawMe(canvas);
        outline49.drawMe(canvas);
        outline50.drawMe(canvas);
        outline51.drawMe(canvas);
        outline52.drawMe(canvas);
        outline53.drawMe(canvas);
        outline54.drawMe(canvas);
        outline55.drawMe(canvas);
        outline56.drawMe(canvas);
        outline57.drawMe(canvas);
        outline58.drawMe(canvas);
        outline59.drawMe(canvas);
        outline60.drawMe(canvas);
        outline61.drawMe(canvas);
        outline62.drawMe(canvas);
        outline63.drawMe(canvas);
        outline64.drawMe(canvas);
        outline65.drawMe(canvas);
        outline66.drawMe(canvas);
        outline67.drawMe(canvas);
        outline68.drawMe(canvas);
        outline69.drawMe(canvas);
        outline70.drawMe(canvas);
        outline71.drawMe(canvas);
        outline72.drawMe(canvas);
        outline73.drawMe(canvas);
        outline74.drawMe(canvas);
        outline75.drawMe(canvas);
        outline76.drawMe(canvas);
        outline77.drawMe(canvas);
        outline78.drawMe(canvas);
        outline79.drawMe(canvas);
        outline80.drawMe(canvas);
        outline81.drawMe(canvas);
        outline82.drawMe(canvas);
        outline83.drawMe(canvas);
        outline84.drawMe(canvas);
        outline85.drawMe(canvas);
        outline86.drawMe(canvas);
        outline87.drawMe(canvas);
        outline88.drawMe(canvas);
        outline89.drawMe(canvas);
        outline90.drawMe(canvas);
        outline91.drawMe(canvas);
        outline92.drawMe(canvas);
        outline93.drawMe(canvas);
        outline94.drawMe(canvas);
        outline95.drawMe(canvas);
        outline96.drawMe(canvas);
        outline97.drawMe(canvas);
        outline98.drawMe(canvas);
        outline99.drawMe(canvas);
        outline100.drawMe(canvas);
        outline101.drawMe(canvas);
        outline102.drawMe(canvas);
        outline103.drawMe(canvas);
        outline104.drawMe(canvas);
        outline105.drawMe(canvas);
        outline106.drawMe(canvas);
        outline107.drawMe(canvas);
        outline108.drawMe(canvas);
        outline109.drawMe(canvas);
        outline110.drawMe(canvas);
        outline111.drawMe(canvas);
        outline112.drawMe(canvas);
        outline113.drawMe(canvas);
        outline114.drawMe(canvas);
        outline115.drawMe(canvas);
        outline116.drawMe(canvas);
        outline117.drawMe(canvas);
        outline118.drawMe(canvas);
        outline119.drawMe(canvas);
        outline120.drawMe(canvas);
        outline121.drawMe(canvas);
        outline122.drawMe(canvas);
        outline123.drawMe(canvas);
        outline124.drawMe(canvas);
        outline125.drawMe(canvas);
        outline126.drawMe(canvas);
        outline127.drawMe(canvas);
        outline128.drawMe(canvas);
        outline129.drawMe(canvas);
        outline130.drawMe(canvas);
        outline131.drawMe(canvas);
        outline132.drawMe(canvas);
        outline133.drawMe(canvas);
        outline134.drawMe(canvas);
        outline135.drawMe(canvas);
        outline136.drawMe(canvas);
        outline137.drawMe(canvas);
        outline138.drawMe(canvas);
        outline139.drawMe(canvas);
        outline140.drawMe(canvas);
        outline141.drawMe(canvas);
        outline142.drawMe(canvas);
        outline143.drawMe(canvas);
        outline144.drawMe(canvas);
        outline145.drawMe(canvas);
        outline146.drawMe(canvas);
        outline147.drawMe(canvas);
        outline148.drawMe(canvas);
        outline149.drawMe(canvas);
        outline150.drawMe(canvas);
        outline151.drawMe(canvas);
        outline152.drawMe(canvas);
        outline153.drawMe(canvas);
        outline154.drawMe(canvas);
        outline155.drawMe(canvas);
        outline156.drawMe(canvas);
        outline157.drawMe(canvas);
        outline158.drawMe(canvas);
        outline159.drawMe(canvas);
        outline160.drawMe(canvas);
        outline161.drawMe(canvas);
        outline162.drawMe(canvas);
        outline163.drawMe(canvas);
        outline164.drawMe(canvas);
        outline165.drawMe(canvas);
        outline166.drawMe(canvas);
        outline167.drawMe(canvas);
        outline168.drawMe(canvas);
        outline169.drawMe(canvas);
        outline170.drawMe(canvas);
        outline171.drawMe(canvas);
        outline172.drawMe(canvas);
        outline173.drawMe(canvas);
        outline174.drawMe(canvas);
        outline175.drawMe(canvas);
        outline176.drawMe(canvas);
        outline177.drawMe(canvas);
        outline178.drawMe(canvas);
        outline179.drawMe(canvas);
        outline180.drawMe(canvas);
        outline181.drawMe(canvas);
        outline182.drawMe(canvas);
        outline183.drawMe(canvas);
        outline184.drawMe(canvas);
        outline185.drawMe(canvas);
        outline186.drawMe(canvas);
        outline187.drawMe(canvas);
        outline188.drawMe(canvas);
        outline189.drawMe(canvas);
        outline190.drawMe(canvas);
        outline191.drawMe(canvas);
        outline192.drawMe(canvas);
        outline193.drawMe(canvas);
        outline194.drawMe(canvas);
        outline195.drawMe(canvas);
        outline196.drawMe(canvas);
        outline197.drawMe(canvas);
        outline198.drawMe(canvas);
        outline199.drawMe(canvas);
        outline200.drawMe(canvas);
        outline201.drawMe(canvas);
        outline202.drawMe(canvas);
        outline203.drawMe(canvas);
        outline204.drawMe(canvas);
        outline205.drawMe(canvas);
        outline206.drawMe(canvas);
        outline207.drawMe(canvas);
        outline208.drawMe(canvas);
        outline209.drawMe(canvas);
        outline210.drawMe(canvas);
        outline211.drawMe(canvas);
        outline212.drawMe(canvas);
        outline213.drawMe(canvas);
        outline214.drawMe(canvas);
        outline215.drawMe(canvas);
        outline216.drawMe(canvas);
        outline217.drawMe(canvas);
        outline218.drawMe(canvas);
        outline219.drawMe(canvas);
        outline220.drawMe(canvas);
        outline221.drawMe(canvas);
        outline222.drawMe(canvas);
        outline223.drawMe(canvas);
        outline224.drawMe(canvas);
        outline225.drawMe(canvas);
        outline226.drawMe(canvas);
        outline227.drawMe(canvas);
        outline228.drawMe(canvas);
        outline229.drawMe(canvas);
        outline230.drawMe(canvas);
        outline231.drawMe(canvas);
        outline232.drawMe(canvas);
        outline233.drawMe(canvas);
        outline234.drawMe(canvas);
        outline235.drawMe(canvas);
        outline236.drawMe(canvas);
        outline237.drawMe(canvas);
        outline238.drawMe(canvas);
        outline239.drawMe(canvas);
        outline240.drawMe(canvas);
        outline241.drawMe(canvas);
        outline242.drawMe(canvas);
        outline243.drawMe(canvas);
        outline244.drawMe(canvas);
        outline245.drawMe(canvas);
        outline246.drawMe(canvas);
        outline247.drawMe(canvas);
        outline248.drawMe(canvas);
        outline249.drawMe(canvas);
        outline250.drawMe(canvas);
        outline251.drawMe(canvas);
        outline252.drawMe(canvas);
        outline253.drawMe(canvas);
        outline254.drawMe(canvas);
        outline255.drawMe(canvas);
        outline256.drawMe(canvas);
        outline257.drawMe(canvas);
        outline258.drawMe(canvas);
        outline259.drawMe(canvas);
        outline260.drawMe(canvas);
        outline261.drawMe(canvas);
        outline262.drawMe(canvas);
        outline263.drawMe(canvas);
        outline264.drawMe(canvas);
        outline265.drawMe(canvas);
        outline266.drawMe(canvas);
        outline267.drawMe(canvas);
        outline268.drawMe(canvas);
        outline269.drawMe(canvas);

        leftCheek0.drawMe(canvas);
        leftCheek1.drawMe(canvas);
        leftCheek2.drawMe(canvas);
        leftCheek3.drawMe(canvas);
        leftCheek4.drawMe(canvas);
        leftCheek5.drawMe(canvas);
        leftCheek6.drawMe(canvas);
        leftCheek7.drawMe(canvas);
        leftCheek8.drawMe(canvas);
        leftCheek9.drawMe(canvas);
        leftCheek10.drawMe(canvas);
        leftCheek11.drawMe(canvas);
        leftCheek12.drawMe(canvas);
        leftCheek13.drawMe(canvas);
        leftCheek14.drawMe(canvas);
        leftCheek15.drawMe(canvas);
        leftCheek16.drawMe(canvas);
        leftCheek17.drawMe(canvas);
        leftCheek18.drawMe(canvas);
        leftCheek19.drawMe(canvas);
        leftCheek20.drawMe(canvas);
        leftCheek21.drawMe(canvas);
        leftCheek22.drawMe(canvas);
        leftCheek23.drawMe(canvas);
        leftCheek24.drawMe(canvas);
        leftCheek25.drawMe(canvas);
        leftCheek26.drawMe(canvas);
        leftCheek27.drawMe(canvas);
        leftCheek28.drawMe(canvas);
        leftCheek29.drawMe(canvas);
        leftCheek30.drawMe(canvas);
        leftCheek31.drawMe(canvas);
        leftCheek32.drawMe(canvas);
        leftCheek33.drawMe(canvas);
        leftCheek34.drawMe(canvas);
        leftCheek35.drawMe(canvas);
        leftCheek36.drawMe(canvas);

        rightCheek0.drawMe(canvas);
        rightCheek1.drawMe(canvas);
        rightCheek2.drawMe(canvas);
        rightCheek3.drawMe(canvas);
        rightCheek4.drawMe(canvas);
        rightCheek5.drawMe(canvas);
        rightCheek6.drawMe(canvas);
        rightCheek7.drawMe(canvas);
        rightCheek8.drawMe(canvas);
        rightCheek9.drawMe(canvas);
        rightCheek10.drawMe(canvas);
        rightCheek11.drawMe(canvas);
        rightCheek12.drawMe(canvas);
        rightCheek13.drawMe(canvas);
        rightCheek14.drawMe(canvas);
        rightCheek15.drawMe(canvas);
        rightCheek16.drawMe(canvas);
        rightCheek17.drawMe(canvas);
        rightCheek18.drawMe(canvas);
        rightCheek19.drawMe(canvas);
        rightCheek20.drawMe(canvas);
        rightCheek21.drawMe(canvas);
        rightCheek22.drawMe(canvas);
        rightCheek23.drawMe(canvas);
        rightCheek24.drawMe(canvas);
        rightCheek25.drawMe(canvas);
        rightCheek26.drawMe(canvas);
        rightCheek27.drawMe(canvas);
        rightCheek28.drawMe(canvas);
        rightCheek29.drawMe(canvas);
        rightCheek30.drawMe(canvas);
        rightCheek31.drawMe(canvas);
        rightCheek32.drawMe(canvas);
        rightCheek33.drawMe(canvas);
        rightCheek34.drawMe(canvas);
        rightCheek35.drawMe(canvas);
        rightCheek36.drawMe(canvas);

        rightEye0.drawMe(canvas);
        rightEye1.drawMe(canvas);
        rightEye2.drawMe(canvas);
        rightEye3.drawMe(canvas);
        rightEye4.drawMe(canvas);
        rightEye5.drawMe(canvas);
        rightEye6.drawMe(canvas);
        rightEye7.drawMe(canvas);
        rightEye8.drawMe(canvas);
        rightEye9.drawMe(canvas);
        rightEye10.drawMe(canvas);
        rightEye11.drawMe(canvas);
        rightEye12.drawMe(canvas);
        rightEye13.drawMe(canvas);
        rightEye14.drawMe(canvas);
        rightEye15.drawMe(canvas);
        rightEye16.drawMe(canvas);
        rightEye17.drawMe(canvas);
        rightEye18.drawMe(canvas);
        rightEye19.drawMe(canvas);
        rightEye20.drawMe(canvas);
        rightEye21.drawMe(canvas);
        rightEye22.drawMe(canvas);
        rightEye23.drawMe(canvas);
        rightEye24.drawMe(canvas);
        rightEye25.drawMe(canvas);
        rightEye26.drawMe(canvas);
        rightEye27.drawMe(canvas);
        rightEye28.drawMe(canvas);
        rightEye29.drawMe(canvas);
        rightEye30.drawMe(canvas);
        rightEye31.drawMe(canvas);
        rightEye32.drawMe(canvas);
        rightEye33.drawMe(canvas);
        rightEye34.drawMe(canvas);
        rightEye35.drawMe(canvas);
        rightEye36.drawMe(canvas);

        leftEye0.drawMe(canvas);
        leftEye1.drawMe(canvas);
        leftEye2.drawMe(canvas);
        leftEye3.drawMe(canvas);
        leftEye4.drawMe(canvas);
        leftEye5.drawMe(canvas);
        leftEye6.drawMe(canvas);
        leftEye7.drawMe(canvas);
        leftEye8.drawMe(canvas);
        leftEye9.drawMe(canvas);
        leftEye10.drawMe(canvas);
        leftEye11.drawMe(canvas);
        leftEye12.drawMe(canvas);
        leftEye13.drawMe(canvas);
        leftEye14.drawMe(canvas);
        leftEye15.drawMe(canvas);
        leftEye16.drawMe(canvas);
        leftEye17.drawMe(canvas);
        leftEye18.drawMe(canvas);
        leftEye19.drawMe(canvas);
        leftEye20.drawMe(canvas);
        leftEye21.drawMe(canvas);
        leftEye22.drawMe(canvas);
        leftEye23.drawMe(canvas);
        leftEye24.drawMe(canvas);
        leftEye25.drawMe(canvas);
        leftEye26.drawMe(canvas);
        leftEye27.drawMe(canvas);
        leftEye28.drawMe(canvas);
        leftEye29.drawMe(canvas);
        leftEye30.drawMe(canvas);
        leftEye31.drawMe(canvas);
        leftEye32.drawMe(canvas);
        leftEye33.drawMe(canvas);
        leftEye34.drawMe(canvas);
        leftEye35.drawMe(canvas);
        leftEye36.drawMe(canvas);


        mouth0.drawMe(canvas);
        mouth1.drawMe(canvas);
        mouth2.drawMe(canvas);
        mouth3.drawMe(canvas);
        mouth4.drawMe(canvas);
        mouth5.drawMe(canvas);
        mouth6.drawMe(canvas);
        mouth7.drawMe(canvas);
        mouth8.drawMe(canvas);
        mouth9.drawMe(canvas);
        mouth10.drawMe(canvas);
        mouth11.drawMe(canvas);
        mouth12.drawMe(canvas);
        mouth13.drawMe(canvas);
        mouth14.drawMe(canvas);
        mouth15.drawMe(canvas);
        mouth16.drawMe(canvas);
        mouth17.drawMe(canvas);
        mouth18.drawMe(canvas);
        mouth19.drawMe(canvas);



    }
    //this is so the game can change the mouth color and to see if it got touched
    //returns an arraylist of all the pixels that make up a mouth

    public ArrayList<CustomRect> getMouth() {
        ArrayList<CustomRect> rectList = new ArrayList<CustomRect>();

        rectList.add(mouth0);
        rectList.add(mouth1);
        rectList.add(mouth2);
        rectList.add(mouth3);
        rectList.add(mouth4);
        rectList.add(mouth5);
        rectList.add(mouth6);
        rectList.add(mouth7);
        rectList.add(mouth8);
        rectList.add(mouth9);
        rectList.add(mouth10);
        rectList.add(mouth11);
        rectList.add(mouth12);
        rectList.add(mouth13);
        rectList.add(mouth14);
        rectList.add(mouth15);
        rectList.add(mouth16);
        rectList.add(mouth17);
        rectList.add(mouth18);
        rectList.add(mouth19);
        






        return rectList;
    }

    //this is so the game can change the left eye color and to see if it got touched
    //returns an arraylist of all the pixels that make up a left eye
    public ArrayList<CustomRect> getLeftEye() {
        ArrayList<CustomRect> rectList = new ArrayList<CustomRect>();

        rectList.add(leftEye0);
        rectList.add(leftEye1);
        rectList.add(leftEye2);
        rectList.add(leftEye3);
        rectList.add(leftEye4);
        rectList.add(leftEye5);
        rectList.add(leftEye6);
        rectList.add(leftEye7);
        rectList.add(leftEye8);
        rectList.add(leftEye9);
        rectList.add(leftEye10);
        rectList.add(leftEye11);
        rectList.add(leftEye12);
        rectList.add(leftEye13);
        rectList.add(leftEye14);
        rectList.add(leftEye15);
        rectList.add(leftEye16);
        rectList.add(leftEye17);
        rectList.add(leftEye18);
        rectList.add(leftEye19);
        rectList.add(leftEye20);
        rectList.add(leftEye21);
        rectList.add(leftEye22);
        rectList.add(leftEye23);
        rectList.add(leftEye24);
        rectList.add(leftEye25);
        rectList.add(leftEye26);
        rectList.add(leftEye27);
        rectList.add(leftEye28);
        rectList.add(leftEye29);
        rectList.add(leftEye30);
        rectList.add(leftEye31);
        rectList.add(leftEye32);
        rectList.add(leftEye33);
        rectList.add(leftEye34);
        rectList.add(leftEye35);
        rectList.add(leftEye36);








        return rectList;
    }

    //this is so the game can change the right eye color and to see if it got touched
    //returns an arraylist of all the pixels that make up a right eye
    public ArrayList<CustomRect> getRightEye() {
        ArrayList<CustomRect> rectList = new ArrayList<CustomRect>();

        rectList.add(rightEye0);
        rectList.add(rightEye1);
        rectList.add(rightEye2);
        rectList.add(rightEye3);
        rectList.add(rightEye4);
        rectList.add(rightEye5);
        rectList.add(rightEye6);
        rectList.add(rightEye7);
        rectList.add(rightEye8);
        rectList.add(rightEye9);
        rectList.add(rightEye10);
        rectList.add(rightEye11);
        rectList.add(rightEye12);
        rectList.add(rightEye13);
        rectList.add(rightEye14);
        rectList.add(rightEye15);
        rectList.add(rightEye16);
        rectList.add(rightEye17);
        rectList.add(rightEye18);
        rectList.add(rightEye19);
        rectList.add(rightEye20);
        rectList.add(rightEye21);
        rectList.add(rightEye22);
        rectList.add(rightEye23);
        rectList.add(rightEye24);
        rectList.add(rightEye25);
        rectList.add(rightEye26);
        rectList.add(rightEye27);
        rectList.add(rightEye28);
        rectList.add(rightEye29);
        rectList.add(rightEye30);
        rectList.add(rightEye31);
        rectList.add(rightEye32);
        rectList.add(rightEye33);
        rectList.add(rightEye34);
        rectList.add(rightEye35);
        rectList.add(rightEye36);
        







        return rectList;
    }


    //this is so the game can change the right cheek color and to see if it got touched
    //returns an arraylist of all the pixels that make up a right cheek
    public ArrayList<CustomRect> getRightCheek() {
        ArrayList<CustomRect> rectList = new ArrayList<CustomRect>();

        rectList.add(rightCheek0);
        rectList.add(rightCheek1);
        rectList.add(rightCheek2);
        rectList.add(rightCheek3);
        rectList.add(rightCheek4);
        rectList.add(rightCheek5);
        rectList.add(rightCheek6);
        rectList.add(rightCheek7);
        rectList.add(rightCheek8);
        rectList.add(rightCheek9);
        rectList.add(rightCheek10);
        rectList.add(rightCheek11);
        rectList.add(rightCheek12);
        rectList.add(rightCheek13);
        rectList.add(rightCheek14);
        rectList.add(rightCheek15);
        rectList.add(rightCheek16);
        rectList.add(rightCheek17);
        rectList.add(rightCheek18);
        rectList.add(rightCheek19);
        rectList.add(rightCheek20);
        rectList.add(rightCheek21);
        rectList.add(rightCheek22);
        rectList.add(rightCheek23);
        rectList.add(rightCheek24);
        rectList.add(rightCheek25);
        rectList.add(rightCheek26);
        rectList.add(rightCheek27);
        rectList.add(rightCheek28);
        rectList.add(rightCheek29);
        rectList.add(rightCheek30);
        rectList.add(rightCheek31);
        rectList.add(rightCheek32);
        rectList.add(rightCheek33);
        rectList.add(rightCheek34);
        rectList.add(rightCheek35);
        rectList.add(rightCheek36);







        return rectList;
    }

    //this is so the game can change the left cheek color and to see if it got touched
    //returns an arraylist of all the pixels that make up a left cheek
    public ArrayList<CustomRect> getLeftCheek() {
        ArrayList<CustomRect> rectList = new ArrayList<CustomRect>();

        rectList.add(leftCheek0);
        rectList.add(leftCheek1);
        rectList.add(leftCheek2);
        rectList.add(leftCheek3);
        rectList.add(leftCheek4);
        rectList.add(leftCheek5);
        rectList.add(leftCheek6);
        rectList.add(leftCheek7);
        rectList.add(leftCheek8);
        rectList.add(leftCheek9);
        rectList.add(leftCheek10);
        rectList.add(leftCheek11);
        rectList.add(leftCheek12);
        rectList.add(leftCheek13);
        rectList.add(leftCheek14);
        rectList.add(leftCheek15);
        rectList.add(leftCheek16);
        rectList.add(leftCheek17);
        rectList.add(leftCheek18);
        rectList.add(leftCheek19);
        rectList.add(leftCheek20);
        rectList.add(leftCheek21);
        rectList.add(leftCheek22);
        rectList.add(leftCheek23);
        rectList.add(leftCheek24);
        rectList.add(leftCheek25);
        rectList.add(leftCheek26);
        rectList.add(leftCheek27);
        rectList.add(leftCheek28);
        rectList.add(leftCheek29);
        rectList.add(leftCheek30);
        rectList.add(leftCheek31);
        rectList.add(leftCheek32);
        rectList.add(leftCheek33);
        rectList.add(leftCheek34);
        rectList.add(leftCheek35);
        rectList.add(leftCheek36);






        return rectList;
    }



    //this is so the game can change the outline color and to see if it got touched
    //returns an arraylist of all the pixels that make up a outline of pikachu
    public ArrayList<CustomRect> getOutline() {
        ArrayList<CustomRect> rectList = new ArrayList<CustomRect>();

        rectList.add(outline0);
        rectList.add(outline1);
        rectList.add(outline2);
        rectList.add(outline3);
        rectList.add(outline4);
        rectList.add(outline5);
        rectList.add(outline6);
        rectList.add(outline7);
        rectList.add(outline8);
        rectList.add(outline9);
        rectList.add(outline10);
        rectList.add(outline11);
        rectList.add(outline12);
        rectList.add(outline13);
        rectList.add(outline14);
        rectList.add(outline15);
        rectList.add(outline16);
        rectList.add(outline17);
        rectList.add(outline18);
        rectList.add(outline19);
        rectList.add(outline20);
        rectList.add(outline21);
        rectList.add(outline22);
        rectList.add(outline23);
        rectList.add(outline24);
        rectList.add(outline25);
        rectList.add(outline26);
        rectList.add(outline27);
        rectList.add(outline28);
        rectList.add(outline29);
        rectList.add(outline30);
        rectList.add(outline31);
        rectList.add(outline32);
        rectList.add(outline33);
        rectList.add(outline34);
        rectList.add(outline35);
        rectList.add(outline36);
        rectList.add(outline37);
        rectList.add(outline38);
        rectList.add(outline39);
        rectList.add(outline40);
        rectList.add(outline41);
        rectList.add(outline42);
        rectList.add(outline43);
        rectList.add(outline44);
        rectList.add(outline45);
        rectList.add(outline46);
        rectList.add(outline47);
        rectList.add(outline48);
        rectList.add(outline49);
        rectList.add(outline50);
        rectList.add(outline51);
        rectList.add(outline52);
        rectList.add(outline53);
        rectList.add(outline54);
        rectList.add(outline55);
        rectList.add(outline56);
        rectList.add(outline57);
        rectList.add(outline58);
        rectList.add(outline59);
        rectList.add(outline60);
        rectList.add(outline61);
        rectList.add(outline62);
        rectList.add(outline63);
        rectList.add(outline64);
        rectList.add(outline65);
        rectList.add(outline66);
        rectList.add(outline67);
        rectList.add(outline68);
        rectList.add(outline69);
        rectList.add(outline70);
        rectList.add(outline71);
        rectList.add(outline72);
        rectList.add(outline73);
        rectList.add(outline74);
        rectList.add(outline75);
        rectList.add(outline76);
        rectList.add(outline77);
        rectList.add(outline78);
        rectList.add(outline79);
        rectList.add(outline80);
        rectList.add(outline81);
        rectList.add(outline82);
        rectList.add(outline83);
        rectList.add(outline84);
        rectList.add(outline85);
        rectList.add(outline86);
        rectList.add(outline87);
        rectList.add(outline88);
        rectList.add(outline89);
        rectList.add(outline90);
        rectList.add(outline91);
        rectList.add(outline92);
        rectList.add(outline93);
        rectList.add(outline94);
        rectList.add(outline95);
        rectList.add(outline96);
        rectList.add(outline97);
        rectList.add(outline98);
        rectList.add(outline99);
        rectList.add(outline100);
        rectList.add(outline101);
        rectList.add(outline102);
        rectList.add(outline103);
        rectList.add(outline104);
        rectList.add(outline105);
        rectList.add(outline106);
        rectList.add(outline107);
        rectList.add(outline108);
        rectList.add(outline109);
        rectList.add(outline110);
        rectList.add(outline111);
        rectList.add(outline112);
        rectList.add(outline113);
        rectList.add(outline114);
        rectList.add(outline115);
        rectList.add(outline116);
        rectList.add(outline117);
        rectList.add(outline118);
        rectList.add(outline119);
        rectList.add(outline120);
        rectList.add(outline121);
        rectList.add(outline122);
        rectList.add(outline123);
        rectList.add(outline124);
        rectList.add(outline125);
        rectList.add(outline126);
        rectList.add(outline127);
        rectList.add(outline128);
        rectList.add(outline129);
        rectList.add(outline130);
        rectList.add(outline131);
        rectList.add(outline132);
        rectList.add(outline133);
        rectList.add(outline134);
        rectList.add(outline135);
        rectList.add(outline136);
        rectList.add(outline137);
        rectList.add(outline138);
        rectList.add(outline139);
        rectList.add(outline140);
        rectList.add(outline141);
        rectList.add(outline142);
        rectList.add(outline143);
        rectList.add(outline144);
        rectList.add(outline145);
        rectList.add(outline146);
        rectList.add(outline147);
        rectList.add(outline148);
        rectList.add(outline149);
        rectList.add(outline150);
        rectList.add(outline151);
        rectList.add(outline152);
        rectList.add(outline153);
        rectList.add(outline154);
        rectList.add(outline155);
        rectList.add(outline156);
        rectList.add(outline157);
        rectList.add(outline158);
        rectList.add(outline159);
        rectList.add(outline160);
        rectList.add(outline161);
        rectList.add(outline162);
        rectList.add(outline163);
        rectList.add(outline164);
        rectList.add(outline165);
        rectList.add(outline166);
        rectList.add(outline167);
        rectList.add(outline168);
        rectList.add(outline169);
        rectList.add(outline170);
        rectList.add(outline171);
        rectList.add(outline172);
        rectList.add(outline173);
        rectList.add(outline174);
        rectList.add(outline175);
        rectList.add(outline176);
        rectList.add(outline177);
        rectList.add(outline178);
        rectList.add(outline179);
        rectList.add(outline180);
        rectList.add(outline181);
        rectList.add(outline182);
        rectList.add(outline183);
        rectList.add(outline184);
        rectList.add(outline185);
        rectList.add(outline186);
        rectList.add(outline187);
        rectList.add(outline188);
        rectList.add(outline189);
        rectList.add(outline190);
        rectList.add(outline191);
        rectList.add(outline192);
        rectList.add(outline193);
        rectList.add(outline194);
        rectList.add(outline195);
        rectList.add(outline196);
        rectList.add(outline197);
        rectList.add(outline198);
        rectList.add(outline199);
        rectList.add(outline200);
        rectList.add(outline201);
        rectList.add(outline202);
        rectList.add(outline203);
        rectList.add(outline204);
        rectList.add(outline205);
        rectList.add(outline206);
        rectList.add(outline207);
        rectList.add(outline208);
        rectList.add(outline209);
        rectList.add(outline210);
        rectList.add(outline211);
        rectList.add(outline212);
        rectList.add(outline213);
        rectList.add(outline214);
        rectList.add(outline215);
        rectList.add(outline216);
        rectList.add(outline217);
        rectList.add(outline218);
        rectList.add(outline219);
        rectList.add(outline220);
        rectList.add(outline221);
        rectList.add(outline222);
        rectList.add(outline223);
        rectList.add(outline224);
        rectList.add(outline225);
        rectList.add(outline226);
        rectList.add(outline227);
        rectList.add(outline228);
        rectList.add(outline229);
        rectList.add(outline230);
        rectList.add(outline231);
        rectList.add(outline232);
        rectList.add(outline233);
        rectList.add(outline234);
        rectList.add(outline235);
        rectList.add(outline236);
        rectList.add(outline237);
        rectList.add(outline238);
        rectList.add(outline239);
        rectList.add(outline240);
        rectList.add(outline241);
        rectList.add(outline242);
        rectList.add(outline243);
        rectList.add(outline244);
        rectList.add(outline245);
        rectList.add(outline246);
        rectList.add(outline247);
        rectList.add(outline248);
        rectList.add(outline249);
        rectList.add(outline250);
        rectList.add(outline251);
        rectList.add(outline252);
        rectList.add(outline253);
        rectList.add(outline254);
        rectList.add(outline255);
        rectList.add(outline256);
        rectList.add(outline257);
        rectList.add(outline258);
        rectList.add(outline259);
        rectList.add(outline260);
        rectList.add(outline261);
        rectList.add(outline262);
        rectList.add(outline263);
        rectList.add(outline264);
        rectList.add(outline265);
        rectList.add(outline266);
        rectList.add(outline267);
        rectList.add(outline268);
        rectList.add(outline269);


        return rectList;
    }





}
